//-----------------------------------------------------------------------------
// mn_errs.h
//-----------------------------------------------------------------------------
// Copyright 2005 Silicon Laboratories, Inc.
//
// Description:
// 	This file contains error code constants defined by the TCP/IP Stack.
//
// Generated by TCP/IP Configuration Wizard Version 3.0.
//

#ifndef  MN_ERRS_H
#define  MN_ERRS_H   1

#include "mn_userconst.h"
#include "mn_stackconst.h"

//-----------------------------------------------------------------------------
// Error Codes
//-----------------------------------------------------------------------------
//
// These error codes are returned by functions in the stack when a failure or
// error occurs.
//

#define NOT_ENOUGH_SOCKETS       -128
#define SOCKET_ALREADY_EXISTS    -127
#define NOT_SUPPORTED            -126
#define PPP_OPEN_FAILED          -125
#define TCP_OPEN_FAILED          -124
#define BAD_SOCKET_DATA          -123
#define SOCKET_NOT_FOUND         -122
#define SOCKET_TIMED_OUT         -121
#define BAD_IP_HEADER            -120
#define NEED_TO_LISTEN           -119
#define RECV_TIMED_OUT           -118
#define ETHER_INIT_ERROR         -117
#define ETHER_SEND_ERROR         -116
#define ETHER_RECV_ERROR         -115
#define NEED_TO_SEND             -114
#define UNABLE_TO_SEND           -113
#define VFILE_ENTRY_IN_USE       -112
#define TFTP_FILE_NOT_FOUND      -111
#define TFTP_NO_FILE_SPECIFIED   -110
#define TFTP_FILE_TOO_BIG        -109
#define TFTP_FAILED              -108
#define SMTP_ALREADY_OPEN        -107
#define SMTP_OPEN_FAILED         -106
#define SMTP_NOT_OPEN            -105
#define SMTP_BAD_PARAM_ERR       -104
#define SMTP_ERROR               -103
#define NEED_TO_EXIT             -102
#define FTP_FILE_MAXOUT          -101
#define DHCP_ERROR               -100
#define DHCP_LEASE_EXPIRED       -99
#define PPP_LINK_DOWN            -98
#define GET_FUNC_ERROR           -97
#define FTP_SERVER_DOWN          -96
#define ARP_REQUEST_FAILED       -95
#define NEED_IGNORE_PACKET       -94
#define TASK_DID_NOT_START       -93
#define DHCP_LEASE_RENEWING      -92
#define IGMP_ERROR               -91
#define MN_INIT_ERROR            -90
#define MN_VERIFY_ERROR          -89
#define INVALID_DUPLEX_MODE      -88
#define INVALID_MAC_ADDRESS      -87
#define AUTO_NEG_FAIL            -86
#define LINK_FAIL                -85

// TCP error codes
#define TCP_ERROR       -1
#define TCP_TOO_LONG    -2
#define TCP_BAD_HEADER  -3
#define TCP_BAD_CSUM    -4
#define TCP_BAD_FCS     -5
#define TCP_NO_CONNECT  -6

// UDP error codes
#define UDP_ERROR       -1
#define UDP_BAD_CSUM    -4
#define UDP_BAD_FCS     -5

//-----------------------------------------------------------------------------
// Error Messages
//-----------------------------------------------------------------------------
//
// These error messages will be given at compilation if invalid values are
// selected for constants.
// 

#if (num_sockets < 2)
#error At least two sockets are required when using ARP or PING
#endif

#if (num_sockets < 1 || num_sockets > 127)
#error Number of sockets must be between 1 and 127
#endif

#if (recv_buff_size < 64)
#error recv_buff_size is too small!
#endif

#if (xmit_buff_size < 64)
#error xmit_buff_size is too small!
#endif

#if (tcp_window > recv_buff_size)
#error tcp_window too large for buffers
#endif

#if (http_buffer_len < tcp_window)
#error http_buffer_len is too small
#endif

#if (arp_cache_size < 1 || arp_cache_size > 255)
#error Invalid arp_cache_size
#endif

#endif   // MN_ERRS_H